#!/bin/bash
source $(dirname "$0")/include

rm -Rf ${BUILD}/acme
mkdir -p ${BUILD}/acme
cd ${BUILD}/acme

${SOURCE}/acme/configure --target=pic30-coff --prefix=${TARGET}
make -j 8
make install

#${SOURCE}/acme/configure --target=pic30-elf --prefix=${TARGET}
#make -j 8
#make install

exit 0
