#!/bin/bash
source $(dirname "$0")/include

rm -Rf ${BUILD}
mkdir -p ${BUILD}

rm -Rf ${TARGET}
mkdir -p ${NONFREE}
cp -R ${MICROCHIP}/* ${NONFREE}

rm -Rf ${SRCDIR}
mkdir -p ${SRCDIR}
cd ${SRCDIR}
unzip -qq ${CWD}/${ZIP}

patch -b -p0 < ${CWD}/patches/c30/c30_flag_definitions.h.diff

patch -b -p0 < ${CWD}/patches/acme/coff-pic30.c.diff
patch -b -p0 < ${CWD}/patches/acme/elf32-pic30.c.diff
patch -b -p0 < ${CWD}/patches/acme/cpu-pic30.c.diff

patch -b -p0 < ${CWD}/patches/gcc/config.gcc.diff
patch -b -p0 < ${CWD}/patches/gcc/configure.diff
patch -b -p0 < ${CWD}/patches/gcc/gcc.c.diff
patch -b -p0 < ${CWD}/patches/gcc/make-relative-prefix.c.diff
patch -b -p0 < ${CWD}/patches/gcc/pic30.c.diff
patch -b -p0 < ${CWD}/patches/gcc/pic30.h.diff

exit 0
